#!/bin/bash

if  [[ $# < 1 ]]
then
	echo "Usage: failover_init <target ip>"
	exit 1
fi

echo "# Setting up arp-failover for host $1"

echo "# Enabling promiscuous mode."
sudo ifconfig eth0 promisc

echo "# Adding alias address 13.37.13.37"
sudo ifconfig eth0:0 13.37.13.37 netmask 255.255.255.255 up

echo "# Flushing old iptable nat rules. "
read -p "Are you sure? (y/n)"  -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
sudo iptables -t nat -F

echo "# Adding Iptables nat rules."
sudo iptables -t nat -A PREROUTING -d $1 -j DNAT --to-destination 13.37.13.37
sudo iptables -t nat -A POSTROUTING -s 13.37.13.37 -j SNAT --to-source $1
