#!/bin/bash

if  [[ $# < 4 ]]
then
	echo "Usage: failover <interface> <source ip> <target ip> <target hw>"
	echo "Example: failover eth0 10.0.0.137 10.0.0.11 b8:27:eb:b1:76:df"
	exit 1
fi

./failover_init $1 $3

cd py-src/

./failover.py $1 $2 $3 $4

cd ..
