#!/bin/bash

if  [[ $# < 3 ]]
then
	echo "Usage: failover <interface> <source ip> <target ip>"
	echo "Example: failover eth0 192.168.1.76 192.168.1.202"
	exit 1
fi

./failover_init $1 $3

cd py-src/

./failover.py $1 $2 $3

cd ..
